CREATE TABLE IF NOT EXISTS user_homepages (
    homepage_id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    template_type VARCHAR(50) NOT NULL DEFAULT 'GITHUB_DEFAULT',
    layout_mode VARCHAR(20) NOT NULL DEFAULT 'default',
    theme_config TEXT NULL,
    custom_code_draft MEDIUMTEXT NULL,
    media_layout_draft MEDIUMTEXT NULL,
    published_template_type VARCHAR(50) NOT NULL DEFAULT 'GITHUB_DEFAULT',
    published_layout_mode VARCHAR(20) NOT NULL DEFAULT 'default',
    published_theme_config TEXT NULL,
    published_custom_code MEDIUMTEXT NULL,
    published_media_layout MEDIUMTEXT NULL,
    published_version INT UNSIGNED NOT NULL DEFAULT 0,
    review_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    submitted_at DATETIME NULL,
    review_deadline_at DATETIME NULL,
    reviewed_by BIGINT UNSIGNED NULL,
    reviewed_at DATETIME NULL,
    review_comment VARCHAR(500) NULL,
    community_template_id BIGINT UNSIGNED NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_user_homepages_user_id (user_id),
    KEY idx_user_homepages_review (review_status, submitted_at),
    KEY idx_user_homepages_template (community_template_id),
    CONSTRAINT fk_user_homepages_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_homepages_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users (user_id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='Personal homepage drafts and published versions';

CREATE TABLE IF NOT EXISTS community_homepage_designs (
    design_id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    author_id BIGINT UNSIGNED NOT NULL,
    source_homepage_id BIGINT UNSIGNED NULL,
    title VARCHAR(120) NOT NULL,
    summary VARCHAR(300) NULL,
    template_type VARCHAR(50) NOT NULL DEFAULT 'GITHUB_DEFAULT',
    layout_mode VARCHAR(20) NOT NULL DEFAULT 'default',
    theme_config TEXT NULL,
    custom_code MEDIUMTEXT NULL,
    media_layout MEDIUMTEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    submitted_at DATETIME NULL,
    review_deadline_at DATETIME NULL,
    reviewed_by BIGINT UNSIGNED NULL,
    reviewed_at DATETIME NULL,
    review_comment VARCHAR(500) NULL,
    clone_count INT UNSIGNED NOT NULL DEFAULT 0,
    like_count INT UNSIGNED NOT NULL DEFAULT 0,
    favorite_count INT UNSIGNED NOT NULL DEFAULT 0,
    comment_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_community_homepages_status (status, created_time DESC),
    KEY idx_community_homepages_author (author_id, created_time DESC),
    KEY idx_community_homepages_review (status, submitted_at),
    FULLTEXT KEY ft_community_homepages_search (title, summary),
    CONSTRAINT fk_community_homepages_author_id FOREIGN KEY (author_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_community_homepages_source_id FOREIGN KEY (source_homepage_id) REFERENCES user_homepages (homepage_id) ON DELETE SET NULL,
    CONSTRAINT fk_community_homepages_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users (user_id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='Community-shareable homepage designs';
